const FETCH_START = 'FETCH_START';
const FETCH_COMPLETE = 'FETCH_COMPLETE';
const FETCH_PENDING = 'FETCH_PENDING';
const FETCH_ERROR = 'FETCH_ERROR';
const BOOKMARKS_ADDED = 'BOOKMARKS_ADDED';
const BOOKMARKS_REMOVED = 'BOOKMARKS_REMOVED';
const BOOKMARKS_PENDING = 'BOOKMARKS_PENDING';

export {
  FETCH_START,
  FETCH_COMPLETE,
  FETCH_PENDING,
  FETCH_ERROR,
  BOOKMARKS_ADDED,
  BOOKMARKS_REMOVED,
  BOOKMARKS_PENDING,
};
