const FETCH_START = 'FETCH_START';
const FETCH_COMPLETE = 'FETCH_COMPLETE';
const FETCH_PENDING = 'FETCH_PENDING';
const FETCH_ERROR = 'FETCH_ERROR';

export { FETCH_START, FETCH_COMPLETE, FETCH_PENDING, FETCH_ERROR };
