const FETCH_START = 'FETCH_START';
const FETCH_COMPLETE = 'FETCH_COMPLETE';
const FETCH_PENDING = 'FETCH_PENDING';
const FETCH_ERROR = 'FETCH_ERROR';
const FETCH_DETAILS_START = 'FETCH_DETAILS_START';
const FETCH_DETAILS_COMPLETE = 'FETCH_DETAILS_COMPLETE';
const FETCH_DETAILS_PENDING = 'FETCH_DETAILS_PENDING';
const FETCH_DETAILS_ERROR = 'FETCH_DETAILS_ERROR';
const FETCH_SIMILAR_PENDING = 'FETCH_SIMILAR_PENDING';
const FETCH_SIMILAR_COMPLETE = 'FETCH_SIMILAR_COMPLETE';
const FETCH_SIMILAR_ERROR = 'FETCH_SIMILAR_ERROR';
const BOOKMARKS_COMPLETE = 'BOOKMARKS_COMPLETE';
const BOOKMARKS_ADDED = 'BOOKMARKS_ADDED';
const BOOKMARKS_REMOVED = 'BOOKMARKS_REMOVED';
const BOOKMARKS_PENDING = 'BOOKMARKS_PENDING';

export {
  FETCH_START,
  FETCH_COMPLETE,
  FETCH_PENDING,
  FETCH_ERROR,
  FETCH_DETAILS_START,
  FETCH_DETAILS_COMPLETE,
  FETCH_DETAILS_PENDING,
  FETCH_DETAILS_ERROR,
  FETCH_SIMILAR_PENDING,
  FETCH_SIMILAR_COMPLETE,
  FETCH_SIMILAR_ERROR,
  BOOKMARKS_COMPLETE,
  BOOKMARKS_ADDED,
  BOOKMARKS_REMOVED,
  BOOKMARKS_PENDING,
};
